on: [push]

jobs:
  ci:
    runs-on: ubuntu-26.04-arm
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: 3.14
          cache: pip
      - run: make ci
